In [11]:
import torch

In [12]:
torch.manual_seed(42)
logits = torch.randn(10, 2)
logits[0, 0] = 100
logits[0, 1] = -100
probas = logits.softmax(-1)
entropy = - torch.sum(probas * probas.log(), dim=-1)
entropy

tensor([   nan, 0.1900, 0.4003, 0.6050, 0.5738, 0.6299, 0.6839, 0.5597, 0.6922,
        0.4918])

In [16]:
from dal_toolbox.metrics.ood import entropy_from_logits

# numerical stable
log_probas = logits.log_softmax(dim=-1)
entropy = - torch.sum(log_probas.exp() * log_probas, dim=-1)
entropy

tensor([-0.0000, 0.1900, 0.4003, 0.6050, 0.5738, 0.6299, 0.6839, 0.5597, 0.6922,
        0.4918])

In [17]:
from dal_toolbox.metrics.ood import entropy_fn, entropy_from_logits
entropy, entropy_fn(probas), entropy_from_logits(logits)

(tensor([-0.0000, 0.1900, 0.4003, 0.6050, 0.5738, 0.6299, 0.6839, 0.5597, 0.6922,
         0.4918]),
 tensor([2.0197e-06, 1.9002e-01, 4.0035e-01, 6.0501e-01, 5.7376e-01, 6.2995e-01,
         6.8389e-01, 5.5969e-01, 6.9222e-01, 4.9180e-01]),
 tensor([-0.0000, 0.1900, 0.4003, 0.6050, 0.5738, 0.6299, 0.6839, 0.5597, 0.6922,
         0.4918]))

In [18]:
torch.manual_seed(42)
logits = torch.randn(10, 2)
logits[0, 0] = 100
logits[0, 1] = -100


# log(p)
# log(1/M sum_m exp log p_m)
# log(sum_m exp log p_m) - log M

In [60]:
import math
logits = torch.randn(3, 2, 2)
ensemble_size = logits.size(1)
logits[0, 0, 0] = 1
logits[0, 0, 1] = 0
logits[0, 1, 0] = 1
logits[0, 1, 1] = 0

log_probas = torch.logsumexp(logits.log_softmax(-1), dim=1) - math.log(ensemble_size)
probas = log_probas.exp()
print(probas)
print('Entropy:', - torch.sum(probas * log_probas, dim=-1))

probas = logits.softmax(-1).mean(1)
print(probas)
print('Entropy', - torch.sum(probas * probas.log(), dim=-1))


tensor([[0.7311, 0.2689],
        [0.4827, 0.5173],
        [0.5394, 0.4606]])
Entropy: tensor([0.5822, 0.6925, 0.6900])
tensor([[0.7311, 0.2689],
        [0.4827, 0.5173],
        [0.5394, 0.4606]])
Entropy tensor([0.5822, 0.6925, 0.6900])
